 # NOTE 'CMAKE_SYSTEM_NAME' and 'CMAKE_SYSTEM_PROCESSOR'
 # are set in cmake presets
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

list(APPEND CMAKE_LIBRARY_PATH "/usr/arm-linux-gnueabihf/lib")
