name: auto-clang-format
on:
  pull_request:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: "."
          exclude: "./third_party ./external"
          extensions: "h,cpp,c,hpp"
          clangFormatVersion: 20
          inplace: True
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: "Committing clang-format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
